name: kcl run

on:
  push:
    branches:
    - main
  pull_request:


jobs:
  kcl-run:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: 
        - macos-12
        - macos-13
        - macos-14
        - macos-14-large
        - macos-13-xlarge
        - macos-14-xlarge
    steps:
    - name: setup kcl
      run: |
        wget -q https://kcl-lang.io/script/install-cli.sh -O - | /bin/bash
    - uses: actions/checkout@v4
    - name: run
      run: |
        kcl run
